export interface Recipe {
    id: string;
    title: string;
    type?: 'VG' | 'VT' | 'MO' | Array<'VG' | 'VT' | 'MO'>;
    category: string;
    description: string;
    prepTime: string;
    cookTime: string;
    servings: number;
    ingredients: string[];
    instructions: string[];
    notes?: string;
}

export const recipes: Recipe[] = [
    {
        id: 'beef-stroganoff',
        title: 'Beef Stroganoff',
        category: 'Main',
        description: 'My simplified version',
        prepTime: '5 minutes',
        cookTime: '30 minutes',
        servings: 2,
        ingredients: [
            '500g stir fry beef strips',
            '1 small onion, chopped',
            'Can of champignons',
            '2 tablespoons sour cream',
            'Beef stock',
            '1 teaspoon salt',
            '1 teaspoon paprika',
            '1 teaspoon onion powder',
        ],
        instructions: [
            'Mix onions, beef, and seasoning ingredients',
            'Fry until beef browns',
            'Add champignons and stock',
            'Once reduced, turn off heat and stir in cream',
        ],
    },
    {
        id: 'banana-and-coconut-cookies',
        type: 'VG',
        title: 'Banana and Coconut Cookies',
        category: 'Dessert',
        description: 'Good use for slightly old bananas',
        prepTime: '10 minutes',
        cookTime: '15 minutes',
        servings: 4,
        ingredients: [
            'Overripe bananas',
            '1 cup shredded coconut per banana',
        ],
        instructions: [
            'Preheat oven to 160°C',
            'Mash bananas in bowl',
            'Stir through coconut',
            'Knead into small flat disks',
            'Bake for 15 minutes',
        ],
    },
    {
        id: 'bread-and-butter-pudding',
        type: 'VT',
        title: 'Bread and Butter Pudding',
        category: 'Dessert',
        description: 'Good use for slightly old bread',
        prepTime: '10 minutes',
        cookTime: '45 minutes',
        servings: 3,
        ingredients: [
            '8 pieces of bread, buttered',
            '3 eggs',
            '1 cup milk',
            '1 cup sultanas',
        ],
        instructions: [
            'Preheat oven to 160°C',
            'Mix the eggs, milk, and sultanas',
            'Cut bread into triangles and soak in mixture for 5 minutes',
            'Stack in small oven proof container and cook for 45 minutes',
        ],
    },
    {
        id: 'crepes',
        type: 'VG',
        title: 'Crepes',
        category: 'Sides',
        description: 'Crepes made with tofu and oats rather than eggs, savoury but can be made sweet instead',
        prepTime: '10 minutes',
        cookTime: '10 minutes',
        servings: 2,
        ingredients: [
            '300g silken tofu',
            '2 cups rolled oats',
            '1/3 cup barista oat milk',
            '1/2 cup kimchi',
            'Cooking oil e.g. macadamia nut',
        ],
        instructions: [
            'Blend ingredients (other than oil) on low for a short time until there are no more whole oats',
            'Heat oil in large flat frying pan',
            'Pour batter as thinly as possible onto a pan (if you need multiple batches blend waiting mix with more oat milk to stop it from thickening)',
            'Cook for around 3 minutes per side',
        ],
        notes: 'As an alternative mix, replace the kimchi with honey and vanilla extract for sweet crepes'
    },
    {
        id: 'cucumber-slices',
        type: 'VG',
        title: 'Cucumber Slices',
        category: 'Sides',
        description: 'Goes well with Miso Salmon',
        prepTime: 'Overnight',
        cookTime: 'None',
        servings: 8,
        ingredients: [
            '2 lebanese cucumber',
            '3 tablespoons rice wine vinegar',
            '1 teaspoon sesame oil',
        ],
        instructions: [
            'Peel and thinly slice cucumber',
            'Put in jar and mix with with rice wine vinegar and sesame oil',
            'Leave in fridge overnight',
        ],
    },
    {
        id: 'lime-salmon',
        title: 'Lime Salmon',
        category: 'Main',
        description: 'Quicker and lighter alternative to Miso Salmon',
        prepTime: '15 minutes',
        cookTime: '25 minutes',
        servings: 2,
        ingredients: [
            '3 salmon fillets, skin on',
            '2 zucchini',
            '1 lime',
            '1 avocado in chunks',
            'Salt and oil',
        ],
        instructions: [
            'Preheat oven to 170°C',
            'Mix the salt, oil, and lime juice',
            'Dip each of the salmon and then add extra salt to the skin',
            'Bake the salmon for 25 minutes',
            'While cooking, slice the zucchini lengthwise. Dip and fry them until brown',
            'Serve with avocado chunks',
        ],
    },
    {
        id: 'mediterranean-salad',
        type: 'VT',
        title: 'Mediterranean Salad',
        category: 'Sides',
        description: 'Goes well with the Moussaka',
        prepTime: '5 minutes',
        cookTime: '5 minutes',
        servings: 4,
        ingredients: [
            '300g mixed baby salad leaves',
            '100g black sliced olives',
            '200g broken feta',
            '100g sun-dried tomato, sliced',
            '100g halloumi',
            '100g anchovies',
        ],
        instructions: [
            'Fry halloumi and anchovies for 5 minutes',
            'Mix with remaining ingredients',
        ],
    },
    {
        id: 'miso-salmon',
        title: 'Miso Salmon',
        category: 'Main',
        description: 'Not as good as Nobu',
        prepTime: 'Overnight',
        cookTime: '25 minutes',
        servings: 2,
        ingredients: [
            '3 pieces skin on salmon',
            '2 carrots sliced julienne',
            '2 tablespoons aka miso paste',
            '3 tablespoons Mirin',
            '1 tablespoon of any nice tasting cheap sake',
            '1 teaspoon sesame oil',
            '1 teaspoon salt',
            'Oil or butter for greasing',
        ],
        instructions: [
            'Mix the mirin, sake, seasame oil, salt, and miso in a bowl',
            'Coat the bottom of each salmon piece in this mix, as well as the carrots, using 3/4 the mix',
            'Place the remaining mix in the fridge overnight, along with the salmon and carrots in a container to marinate',
            'When ready, preheat oven to 180°C',
            'Grease some foil and cook the salmon uncovered for 10 minutes with the bottom facing up',
            'Remove from oven, flip over, and thinly coat the skin on top with the remaining marinade and some extra salt',
            'Cook for another 15 minutes or until the skin is crispy',
        ],
    },
    {
        id: 'matcha-and-flaxseed-spread',
        type: 'VG',
        title: 'Matcha and Flaxseed Spread',
        category: 'Sides',
        description: 'Savoury spread for crackers, can be sweetened for a dessert topping',
        prepTime: '20 minutes',
        cookTime: 'Overnight',
        servings: 10,
        ingredients: [
            '2 tablespoons matcha powder',
            '2 cups flaxseed',
            '1 1/2 cups barista oat milk',
            '3 tablespoons red bean paste (optional, to sweeten)',
            '3 tablespoons honey (optional, to sweeten)',
        ],
        instructions: [
            'Bring milk to boil and stir through matcha',
            'Stir through flaxseed, then pour into a container and refrigerate until cool',
            'Once cool, add honey and/or red bean paste if you want to sweeten it',
            'Whisk until porridge like',
            'Leave in fridge until it hardens into a spread',
        ],
    },
    {
        id: 'moussaka',
        type: 'VG',
        title: 'Moussaka',
        category: 'Main',
        description: 'Simple version of the modern Greek moussaka with lentils instead of beef',
        prepTime: '30 minutes',
        cookTime: '50 minutes',
        servings: 2,
        ingredients: [
            '5 cloves garlic',
            '2 medium eggplants',
            '120g raw cashews',
            '7g bakers yeast',
            'White onion',
            '1 can lentils',
            '1 can tomatoes',
            'Olive oil',
        ],
        instructions: [
            'Preheat oven to 200°C',
            'Slice ends off garlic and peel off outer layer',
            'Soak in a small amount of olive oil and salt',
            'Wrap in foil and place in oven on tray for 10 minutes',
            'Soak cashews in 1 cup boiling water',
            'Slice eggplant thinly and salt both sides of each slice',
            'Place on paper towels to dry out and then coat both sides with olive oil',
            'Remove the garlic from oven and put the eggplant in the oven for 10 minutes',
            'Place cashews and their water, yeast, and garlic mix in a blender and blend until smooth',
            'Remove eggplant from the oven and line the base of a deep dish with half of it',
            'Slice onion and combine with lentils and tomatoes from can',
            'Heat olive oil in pan and fry the tomato mixture until the juice reduces',
            'Place the mix on top of the eggplant in the deep dish',
            'Cover with the remaining eggplant, and then spread the cashew mix on top of this',
            'Bake for 30 minutes',
        ],
    },
    {
        id: 'nut-slice',
        type: 'VG',
        title: 'Nut Slice',
        category: 'Dessert',
        description: 'Subtly sweet flour-less vegan dessert',
        prepTime: '20 minutes',
        cookTime: '35 minutes',
        servings: 8,
        ingredients: [
            '375g jar of nut butter e.g. ABC spread',
            '1 cup almond flour',
            '2 blocks of milk-less chocolate e.g. Lindt 85%',
            '1 cup barista oat or almond milk',
            'Greaser e.g. macadamia nut oil or vegan butter',
            '(optional) 2 tablespoons of thickener e.g. faba bean powder or ground flaxseed',
            '(optional) 2 tablespoons chopped walnuts or cacao nibs',
            '(optional) 1 teaspoon vanilla extract',
        ],
        instructions: [
            'Grease a medium size deep oven pan e.g. a Loaf Pan',
            'Preheat oven to 180°C',
            'Hand mix ingredients other than chocolate in a large bowl',
            'Heat chocolate in microwave on low heat in microwave safe container until mostly liquid',
            'Immediately mix it through other ingredients before it hardens',
            'Pour into pan and bake for approximately 35 minutes',
        ],
        notes: 'Best served with a plant based cream. It is quite cakey when warm but solidifies into a slice in fridge, either is nice.'
    },
    {
        id: 'shepherds-pie',
        type: ['VT', 'MO'],
        title: 'Shepherd\'s Pie',
        category: 'Main',
        description: 'Cooked plant based mince meat (or lentils) topped with mashed potato',
        prepTime: '45 minutes',
        cookTime: '45 minutes',
        servings: 2,
        ingredients: [
            '1 onion',
            '500g plant based mince',
            '2 carrots',
            '120 grams frozen peas',
            '3 potatoes',
            '120g mozzarella',
            '3 tablespoons butter',
            'Vegetable stock powder',
            'Salt',
            'Garlic salt',
            'Cooking oil e.g. macadamia nut oil',
            'Oil or butter for greasing oven pan',
        ],
        instructions: [
            'Fill large pot half full with water and start boiling',
            'Cut carrots into small squares and combine with peas',
            'Chop onions finely. Add some salt to the boiling water',
            'Peel and quarter potatoes',
            'Add oil and and salt to a frying pan and turn it to high heat',
            'Add potatoes to boiling water',
            'Add mince (or lentils in alternative version) and a pinch of garlic salt to the saucepan',
            'Preheat oven to 180°C',
            'Once mince is heated (wait for brown if using beef mince, or straight away for lentils) add carrot and pea mix',
            'Add stock powder to 1 cup water, mix, and add to frying pan',
            'Mix  mozzarella and butter in microwave proof bowl',
            'Drain and finely mash potatoes. Spread out thinly on large plate',
            'Frying pan mix should now be reduced and heat can be turned off',
            'Microwave parmesan mix and then knead it into spread out potato mash',
            'Grease an oven proof container, pour in mince, and then top with the potato mash',
            'Bake for 45 minutes or until topping starts to brown',
        ],
        notes: 'For the meat based version low fat grass fed beef mince works best, or another vegetarian ' +
            'alternative is to substitute 2 cups of lentils for the mince'
    },
    {
        id: 'stir-fry-tacos',
        title: 'Stir Fry Tacos',
        category: 'Main',
        description: 'If you don\'t like beans they can be replaced by chopped garlic, hard tofu, and soy sauce to make this an asian fusion dish',
        prepTime: '15 minutes',
        cookTime: '25 minutes',
        servings: 2,
        ingredients: [
            '500g grass fed stir fry beef strips',
            '1 tin black beans',
            '1 Old El Paso™ Stand \'N Stuff™ Taco Kit (10 hard shell tacos, spice mix, tomato salsa)',
            '1 carrot',
            '1/2 block haloumi',
            '1/2 cup grated cheese',
            '1/2 cup shredded lettuce',
            'Pinch of paprika and onion powder',
            '100g sour cream',
        ],
        instructions: [
            'Fry beef with onion powder and paprika (replace paprika with garlic if doing asian fusion)',
            'Chop carrot finely and add it to the frying beef',
            'Preheat oven to 180°C',
            'Chop and add haloumi to the frying beef',
            'Add spice mix and beans (replace beans with tofu if doing asian fusion)',
            'Turn off heat and stir through the tomato salsa (replace with soy sauce if doing asian fusion)',
            'Add to oven and cover with grated cheese',
            'Cook for 10 minutes, adding in the taco shells in the last minute to warm them',
            'Serve in the taco shells topped by sour cream and shredded lettuce',
        ],
    },
    {
        id: 'stuffed-eggplant',
        type: 'VG',
        title: 'Stuffed Eggplant',
        category: 'Main',
        description: 'Makes 4 sides or 2 mains',
        prepTime: '20 minutes',
        cookTime: '25 minutes',
        servings: 2,
        ingredients: [
            '2 large eggplants',
            '500g impossible mince',
            '1 zucchini',
            'Pinch of cumin, paprika, onion powder, and salt',
            'Olive oil and brush',
        ],
        instructions: [
            'Slice the eggplant length-ways',
            'Scoop out the flesh. Chop and set aside',
            'Mix olive oil with onion powder and salt, and brush outside of eggplants',
            'Mix eggplant flesh with cumin and paprika',
            'Put eggplant shells into oven at 180°C',
            'Start frying impossible mince with onion powder',
            'Dice the zucchini',
            'Add the eggplant flesh mix to the pan, followed by the zucchini',
            'Add the mix to the cooking shells, and cook for another 15 minutes',
        ],
    },
    {
        id: 'tacos',
        type: 'VT',
        title: 'Tacos',
        category: 'Main',
        description: 'As easy as it gets',
        prepTime: '10 minutes',
        cookTime: '15 minutes',
        servings: 3,
        ingredients: [
            '1 corn cob, stripped',
            '1 carrot, grated',
            '5 mushrooms, chopped',
            '1 small zucchini, chopped',
            '1 tomato, chopped' +
            '12 taco shells + seasoning',
            '1/2 avocado, chopped',
            '1 can black beans',
            '1 can refried beans',
            'Mozzarella',
            'Sour Cream',
            'Oil for frying',
        ],
        instructions: [
            'Heat tacos in oven',
            'Mix avocado, cream, and mozzarella to make a topping',
            'Fry other ingredients',
            'Add to tacos, then add topping',
        ],
    },
];

export function getRecipeById(id: string): Recipe | undefined {
    return recipes.find(r => r.id === id);
}

export function formatTags(recipe: Recipe): string[] {
    return Array.isArray(recipe.type) ? recipe.type : (recipe.type ? [recipe.type] : []);
}
