export interface Movie {
    title: string;
    thumbnail: string;
    summary: string;
    e: number;
    a: number;
    n: number;
    c: number;
}

export const sciFiMoviesData: Movie[] = [
    {
        title: "10 Cloverfield Lane",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/0e/10_Cloverfield_Lane.png",
        summary: ``,
        e: 5,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "12 Monkeys",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/cf/Twelve_monkeysmp.jpg",
        summary: `Gilliam's style is present in every shot, but unlike Brazil this sci-fi has a suspenseful and 
        driven narrative that keeps you hooked until the end`,
        e: 7,
        a: 7,
        n: 8,
        c: 6,
    },
    {
        title: "13th Floor",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/02/The_Thirteenth_Floor_poster.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 6,
        c: 5,
    },
    {
        title: "2001 - A Space Odyssey",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29.png",
        summary: `Brilliant premise and ideas which Kubrick brings to life, but the plotting meanders.`,
        e: 9,
        a: 8,
        n: 3,
        c: 4,
    },
    {
        title: "28 Days Later",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/28_days_later.jpg/330px-28_days_later.jpg",
        summary: ``,
        e: 5,
        a: 8,
        n: 6,
        c: 7,
    },
    {
        title: "28 Weeks Later",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/thumb/4/46/28_Weeks_Later_poster.jpg/330px-28_Weeks_Later_poster.jpg",
        summary: ``,
        e: 4,
        a: 7,
        n: 4,
        c: 3,
    },
    {
        title: "6th Day, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a0/The_6th_Day_%282000_film%29.jpg",
        summary: `Peak Schwarzenegger, the concept is a little ridiculous but it all works`,
        e: 6,
        a: 7,
        n: 5,
        c: 4,
    },
    {
        title: "A.I. Artificial Intelligence",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e6/AI_Poster.jpg",
        summary: `Spielberg's tribute to Kubrick is one of his best films and a great sci-fi, slick entertainment 
        throughout and some great world building on top of some involving and melancholy moments`,
        e: 8,
        a: 8,
        n: 6,
        c: 7,
    },
    {
        title: "Abyss, The (Directors Cut)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/ad/TheAbyss.jpg",
        summary: `Cameron’s deeply technical and atmospheric classic has a somewhat odd storyline which needs to be
         watched with the director's cut ending to make any sense`,
        e: 7,
        a: 7,
        n: 6,
        c: 7,
    },
    {
        title: "Ad Astra",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/cb/Ad_Astra_-_film_poster.jpg",
        summary: ``,
        e: 7,
        a: 9,
        n: 3,
        c: 3,
    },
    {
        title: "Adjustment Bureau, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Adjustment_Bureau_Poster.jpg",
        summary: ``,
        e: 5,
        a: 7,
        n: 7,
        c: 7,
    },
    {
        title: "Advantageous",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/fb/Advantageous_poster.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 4,
        c: 4,
    },
    {
        title: "After Earth",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/5b/After_Earth_Poster.jpg",
        summary: `The Jaden and Will Smith relationship makes this, otherwise average concept`,
        e: 5,
        a: 7,
        n: 7,
        c: 7,
    },
    {
        title: "Alien",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg",
        summary: `Ridley Scott's slow-burning, atmospheric filmmaking melds a first-rate screenplay, Giger's art, and
        Sigourney Weaver's formidable performance into a masterpiece of sci-fi cinema`,
        e: 8,
        a: 10,
        n: 10,
        c: 7,
    },
    {
        title: "Alien 4",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/70/Alien_Resurrection_poster.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 5,
    },
    {
        title: "Alien3",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/b9/Alien3_poster.jpg",
        summary: `Fincher takes the Aliens franchise in a grimmer direction, building a grimy and claustrophobic visual 
        language that ultimately works well despite all the compromises that were made in the direction of this movie`,
        e: 6,
        a: 8,
        n: 9,
        c: 6,
    },
    {
        title: "Alien: Romulus",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/cb/Alien_Romulus_2024_%28poster%29.jpg",
        summary: `An excellently made and worthy neo-sequel to Alien, while in many places it lacks originality it 
        does deliver a believable extension to the world building and claustrophobic atmosphere of the original`,
        e: 7,
        a: 9,
        n: 7,
        c: 6,
    },
    {
        title: "Aliens",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/fb/Aliens_poster.jpg",
        summary: `A textbook sequel which takes the essence of the first and pivots to a larger action movie while 
        keeping the atmosphere, suspense, and strong lead of the original`,
        e: 8,
        a: 9,
        n: 9,
        c: 7,
    },
    {
        title: "Alita: Battle Angel",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/ee/Alita_Battle_Angel_%282019_poster%29.png",
        summary: `Rodriguez high energy directorial style does justice to Yukito Kishiro's cyberpunk spectacle, with
        the movie remaining engaging and confident throughout`,
        e: 7,
        a: 9,
        n: 7,
        c: 7,
    },
    {
        title: "Altitude",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/14/AltitudePoster-1.jpg",
        summary: `Shallow but entertaining and well paced apocalyptic story which goes a bit wrong in the last 20 minutes`,
        e: 4,
        a: 5,
        n: 5,
        c: 6,
    },
    {
        title: "Animatrix, The",
        thumbnail: "https://static.wikia.nocookie.net/toonami/images/8/82/Animatrix.jpg",
        summary: `Directed by some notable animators, The Animatrix was a slick way to add flavour to the Matrix 
        universe via an atmospheric series of short films, which ended up being more enjoyable than the subsequent movies`,
        e: 8,
        a: 9,
        n: 10,
        c: 6,
    },
    {
        title: "Annihilation",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f6/Annihilation_%28film%29.png",
        summary: ``,
        e: 7,
        a: 8,
        n: 5,
        c: 7,
    },
    {
        title: "Anon",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/55/Anon.png",
        summary: ``,
        e: 8,
        a: 7,
        n: 5,
        c: 5,
    },
    {
        title: "Approaching The Unknown",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/06/Approaching_the_Unknown.png",
        summary: ``,
        e: 6,
        a: 5,
        n: 4,
        c: 4,
    },
    {
        title: "Archive",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/09/Archive_%28film%29.jpg",
        summary: `Brings a fresh cyberpunk aesthetic and a decent plot`,
        e: 6,
        a: 8,
        n: 7,
        c: 5,
    },
    {
        title: "Arrival",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg",
        summary: `A graceful adaptation of Ted Chiang's novella, this captures a lot of its fascination with language 
        and time, tying everything together with nuanced performances by the leads and some excellent cinematography.`,
        e: 8,
        a: 8,
        n: 7,
        c: 7,
    },
    {
        title: "Atomica",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/72/Atomica%2C_Official_Poster.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 4,
        c: 2,
    },
    {
        title: "Automata",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/65/Automata_poster.jpg",
        summary: ``,
        e: 6,
        a: 7,
        n: 4,
        c: 4,
    },
    {
        title: "Avatar",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg",
        summary: `This groundbreaking 3D cinematic experience, despite the simple plot, is still enjoyable in 2d due to
        the passion and detail that has clearly gone into each shot and some interesting world building and sci-fi 
        elements to boot`,
        e: 6,
        a: 10,
        n: 8,
        c: 7,
    },
    {
        title: "Back To The Future",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg",
        summary: ``,
        e: 2,
        a: 4,
        n: 6,
        c: 3,
    },
    {
        title: "Battle For Terra",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e2/Battle-for-terra-poster.jpg",
        summary: `A clever and original kids sci-fi with some excellent world building`,
        e: 7,
        a: 9,
        n: 8,
        c: 6,
    },
    {
        title: "Battleship",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/6e/Battleship_Poster.jpg",
        summary: ``,
        e: 2,
        a: 5,
        n: 4,
        c: 3,
    },
    {
        title: "Bicentenial Man",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/fc/Bicentennial_man_film_poster.jpg",
        summary: ``,
        e: 8,
        a: 5,
        n: 5,
        c: 5,
    },
    {
        title: "Blade Runner",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9f/Blade_Runner_%281982_poster%29.png",
        summary: `The beautiful over the top noir cinematography established Scott and the crew's creation as the 
        definitive cyberpunk environment, and although parts of the film are a bit empty the story is compelling and 
        filled with both spectacular scenes and fascinating mundane details courtesy of Syd Mead's background design`,
        e: 8,
        a: 10,
        n: 6,
        c: 7,
    },
    {
        title: "Blade Runner 2049",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png",
        summary: `Villeneuve creates a visually stunning and dark future worthy of the original, which along with 
        Zimmer's score and masterful acting performances creates a magnificent backdrop to an engaging and well 
        thought out screenplay`,
        e: 7,
        a: 10,
        n: 8,
        c: 7,
    },
    {
        title: "Blindness",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/bc/Blindness_%282008_film%29.png",
        summary: ``,
        e: 5,
        a: 5,
        n: 5,
        c: 3,
    },
    {
        title: "Brazil",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e9/Brazil_%281985_film%29_poster.jpg",
        summary: ``,
        e: 7,
        a: 5,
        n: 3,
        c: 4,
    },
    {
        title: "Captive State",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/43/Captive_State_%282019_poster%29.png",
        summary: ``,
        e: 4,
        a: 7,
        n: 5,
        c: 4,
    },
    {
        title: "Cargo",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/7e/Cargo2017poster.jpg",
        summary: ``,
        e: 5,
        a: 5,
        n: 3,
        c: 5,
    },
    {
        title: "Carriers",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/d8/Carriersposter.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 8,
    },
    {
        title: "Chaos Walking",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/63/Chaos_Walking_%28film%29.png",
        summary: ``,
        e: 6,
        a: 6,
        n: 5,
        c: 5,
    },
    {
        title: "Chappie",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/71/Chappie_poster.jpg",
        summary: ``,
        e: 6,
        a: 5,
        n: 8,
        c: 6,
    },
    {
        title: "Children of Men",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Children_of_men_ver4.jpg/330px-Children_of_men_ver4.jpg",
        summary: ``,
        e: 5,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "Chrysalis (2014)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg",
        summary: ``,
        e: 5,
        a: 7,
        n: 5,
        c: 5,
    },
    {
        title: "City of Ember",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/18/City_of_ember.jpg",
        summary: `Slightly satirical sci-fi movie for older kids, nicely designed`,
        e: 7,
        a: 7,
        n: 6,
        c: 7,
    },
    {
        title: "Clone Returns Home, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/42/Playdate_%28film%29_poster.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 3,
        c: 3,
    },
    {
        title: "Cloud Atlas",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/20/Cloud_Atlas_Poster.jpg",
        summary: `A dreamlike, intoxicating epic of intertwined stories, connected from past to future by repeated 
        motifs, with each period lovingly designed and the philosophic themes underpinning them working on some 
        subliminal level even when it is emotionally difficult to connect to some of the stories.`,
        e: 8,
        a: 9,
        n: 7,
        c: 6,
    },
    {
        title: "Cloverfield",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f1/Cloverfield_theatrical_poster.jpg",
        summary: ``,
        e: 4,
        a: 8,
        n: 5,
        c: 5,
    },
    {
        title: "Cloverfield Paradox",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e5/Cloverfield_paradox_poster.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 4,
        c: 5,
    },
    {
        title: "Code 46",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/df/Code_46_movie.jpg",
        summary: ``,
        e: 5,
        a: 5,
        n: 4,
        c: 3,
    },
    {
        title: "Code 8",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/45/Code_8_2019_poster.jpg",
        summary: ``,
        e: 4,
        a: 6,
        n: 6,
        c: 6,
    },
    {
        title: "Coherence",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9d/Coherence_2013_theatrical_poster.jpg",
        summary: ``,
        e: 4,
        a: 4,
        n: 6,
        c: 5,
    },
    {
        title: "Colony, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/d1/The_Colony_Poster.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 5,
        c: 6,
    },
    {
        title: "Congress, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/8d/The_Congress_film_poster.jpg",
        summary: ``,
        e: 8,
        a: 6,
        n: 3,
        c: 6,
    },
    {
        title: "Contact",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/75/Contact_ver2.jpg",
        summary: `A satisfying adaptation of Carl Sagan's novel which digs into the implications of first contact on 
        science and faith`,
        e: 8,
        a: 6,
        n: 7,
        c: 8,
    },
    {
        title: "Contagion",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/86/Contagion_Poster.jpg",
        summary: `Tense disaster movie which was prescient in predicting rapid vaccine development, however it would 
        have been a better movie if some of the characters and subplots were cut`,
        e: 8,
        a: 7,
        n: 7,
        c: 6,
    },
    {
        title: "Containment",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e7/Containment_Poster.jpg",
        summary: ``,
        e: 5,
        a: 7,
        n: 5,
        c: 7,
    },
    {
        title: "Cowboy Bebop: The Movie",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e7/Cowboy_Bebop_Knockin%27_on_Heaven%27s_Door_poster.jpg",
        summary: ``,
        e: 5,
        a: 5,
        n: 3,
        c: 5,
    },
    {
        title: "Creator, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/94/The_Creator_2023_poster.jpg",
        summary: `This visually stunning exploration of a future containing a polity of primitive AIs quickly runs into 
        an uncanny valley of implausibility once we get into the details.`,
        e: 6,
        a: 9,
        n: 6,
        c: 7,
    },
    {
        title: "Cube",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/0c/Cube_The_Movie_Poster_Art.jpg",
        summary: ``,
        e: 7,
        a: 6,
        n: 6,
        c: 4,
    },
    {
        title: "Cypher",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/db/Cyphermovieposter.jpg",
        summary: ``,
        e: 4,
        a: 4,
        n: 6,
        c: 4,
    },
    {
        title: "Dawn of the planet of the apes",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/77/Dawn_of_the_Planet_of_the_Apes.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 6,
    },
    {
        title: "Day The Earth Stood Still, The (2008)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Day_the_Earth_Stood_Still.jpg",
        summary: ``,
        e: 6,
        a: 5,
        n: 5,
        c: 4,
    },
    {
        title: "Day, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9b/The_Day_%28film%29_poster.jpg",
        summary: ``,
        e: 3,
        a: 5,
        n: 4,
        c: 4,
    },
    {
        title: "Deep Blue Sea",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/73/Deep_Blue_Sea_%281999_film%29_poster.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 6,
        c: 5,
    },
    {
        title: "Deep Impact",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/93/Deep_Impact_poster.jpg",
        summary: ``,
        e: 5,
        a: 8,
        n: 6,
        c: 6,
    },
    {
        title: "District 9",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/d7/District_nine_ver2.jpg",
        summary: `The flawed and dysfunctional alien society is more interesting than the apartheid parallels, and the
        characterisation is a bit one dimensional, but this is funny and sad and watchable nonetheless`,
        e: 8,
        a: 6,
        n: 7,
        c: 6,
    },
    {
        title: "Divergent",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/7e/Divergent_film_poster.jpg",
        summary: ``,
        e: 5,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "Donnie Darko",
        thumbnail: "https://www.themoviedb.org/t/p/w1280/3PiQIQzJX2oE8Uw6gjL08BXQRoB.jpg",
        summary: `A weird, soulful film that peels back an outer layer of teenage angst and superficial 80s suburbia to 
        delve into mental illness, quantum physics and time travel, and tie them together into a beautiful piece of art`,
        e: 9,
        a: 7,
        n: 10,
        c: 8,
    },
    {
        title: "Downsizing",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a8/Downsizing.png",
        summary: `Good high concept which wears a little thin but it remains light hearted and watchable throughout`,
        e: 7,
        a: 6,
        n: 7,
        c: 7,
    },
    {
        title: "Dredd",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Dredd2012Poster.jpg/330px-Dredd2012Poster.jpg",
        summary: ``,
        e: 4,
        a: 6,
        n: 7,
        c: 3,
    },
    {
        title: "Dune (1984)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/51/Dune_1984_Poster.jpg",
        summary: ``,
        e: 7,
        a: 4,
        n: 4,
        c: 3,
    },
    {
        title: "Dune (2021)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg",
        summary: `Leaning into the colonial allegories from the source a bit more than the Lynch version works well in 
        creating an engaging and atmospheric adaptation that is well paced and entertaining throughout`,
        e: 8,
        a: 9,
        n: 7,
        c: 6,
    },
    {
        title: "Edge Of Tomorrow",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f9/Edge_of_Tomorrow_Poster.jpg",
        summary: `Beautifully shot action packed movie with a great high concept, characters are a bit of a let down but have their moments`,
        e: 7,
        a: 8,
        n: 8,
        c: 6,
    },
    {
        title: "Elysium",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f9/Elysium_Poster.jpg",
        summary: `Neill Blomkamp continues to pull no punches in this gritty if slightly illogical dystopian vision,
        which is worth watching just for set design and costumes.`,
        e: 7,
        a: 8,
        n: 6,
        c: 7,
    },
    {
        title: "Ender's Game",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/8c/Ender%27s_Game_poster.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 6,
    },
    {
        title: "Escape From L.A",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/71/Escape_From_LA.jpg",
        summary: ``,
        e: 2,
        a: 1,
        n: 1,
        c: 1,
    },
    {
        title: "Europa Report",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/23/Europa_Report_Official_Poster.jpg",
        summary: ``,
        e: 6,
        a: 5,
        n: 5,
        c: 4,
    },
    {
        title: "Eva",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/db/Eva_%282018_film%29.png",
        summary: ``,
        e: 5,
        a: 3,
        n: 3,
        c: 4,
    },
    {
        title: "Event Horizon",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/8c/Event_horizon_ver1.jpg",
        summary: `This well paced sci-fi horror works well as an enjoyable late-night popcorn flick`,
        e: 6,
        a: 9,
        n: 8,
        c: 7,
    },
    {
        title: "Ex Machina",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/ba/Ex-machina-uk-poster.jpg",
        summary: `An excellently paced sci-fi thriller, we are driven through a beautifully atmospheric setting by an 
        extremely compelling idea to the inevitable conclusion, with the conflicting personalities and strength of the
        ideas making this a completely enthralling journey from start to finish.`,
        e: 8,
        a: 8,
        n: 8,
        c: 8,
    },
    {
        title: "External Sunshine of the Spotless Mind",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a4/Eternal_Sunshine_of_the_Spotless_Mind.png",
        summary: ``,
        e: 5,
        a: 3,
        n: 5,
        c: 7,
    },
    {
        title: "Extinction",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/0d/Extinction.png",
        summary: ``,
        e: 7,
        a: 7,
        n: 5,
        c: 5,
    },
    {
        title: "Fahrenheit 451",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f0/Fahrenheit451B.jpg",
        summary: ``,
        e: 6,
        a: 4,
        n: 4,
        c: 3,
    },
    {
        title: "Fifth Element, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/65/Fifth_element_poster_%281997%29.jpg",
        summary: `Visually stunning cinematography, amazing goofball costumes and lines, and thoroughly entertaining 
        from start to finish, there has never been anything else quite like this sci-fi blockbuster`,
        e: 6,
        a: 8,
        n: 10,
        c: 6,
    },
    {
        title: "Forbidden Planet",
        thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Forbiddenplanetposter.jpg/330px-Forbiddenplanetposter.jpg",
        summary: ``,
        e: 7,
        a: 4,
        n: 6,
        c: 3,
    },
    {
        title: "Fountain, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/ee/Fountain_poster_1.jpg",
        summary: `A beautiful and ambitious movie about the quest for eternal life, the story is quite meandering and 
        confusing but the visuals are spectacular`,
        e: 8,
        a: 8,
        n: 5,
        c: 7,
    },
    {
        title: "Gattaca",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/de/Gattaca_poster.jpg",
        summary: `This exploration of the consequences of designer babies is A grade classic science fiction, the 
        setting is a bit uninspired but the brilliant high concept and decent characters pull everything together well 
        enough`,
        e: 9,
        a: 5,
        n: 7,
        c: 7,
    },
    {
        title: "Geostorm",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/76/Geostorm_official_teaser_poster.jpg",
        summary: ``,
        e: 5,
        a: 7,
        n: 4,
        c: 3,
    },
    {
        title: "Ghost In The Shell (2017)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/11/Ghost_in_the_Shell_%282017_film%29.png",
        summary: ``,
        e: 6,
        a: 8,
        n: 5,
        c: 4,
    },
    {
        title: "Ghosts of Mars",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/ff/John_Carpenter%27s_Ghosts_of_Mars.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 5,
        c: 3,
    },
    {
        title: "Giver, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/02/The_Giver_poster.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 4,
        c: 3,
    },
    {
        title: "Godzilla (2014)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg",
        summary: ``,
        e: 5,
        a: 5,
        n: 3,
        c: 3,
    },
    {
        title: "Gorge, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/dc/The_Gorge_%28film%29_poster.jpg",
        summary: `Beautiful scenery and soundtrack with decent characters and novel action/horror/romance/sci-fi concept, however once the pacing picks up it all becomes a bit formulaic`,
        e: 5,
        a: 8,
        n: 7,
        c: 7,
    },
    {
        title: "Gravity",
        thumbnail: "https://www.themoviedb.org/t/p/w1280/krQrQSNb0EXd5L0e2CkoU5V6XNq.jpg",
        summary: `Watching this sci-fi thriller in IMAX was wild, this movie is a completely engrossing white knuckle 
        ride with stunning SFX vistas and a simple compelling plot that is exceptionally well executed by both main 
        characters`,
        e: 7,
        a: 10,
        n: 8,
        c: 8,
    },
    {
        title: "Greenland",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/2a/Greenland_%28film%29.png",
        summary: ``,
        e: 3,
        a: 7,
        n: 6,
        c: 5,
    },
    {
        title: "Hardware",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/d0/Hardwareposter.jpg",
        summary: ``,
        e: 4,
        a: 6,
        n: 4,
        c: 3,
    },
    {
        title: "Hell",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/65/Hell_%282011_film%29_film_poster.jpg",
        summary: ``,
        e: 3,
        a: 5,
        n: 5,
        c: 4,
    },
    {
        title: "Her",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/44/Her2013Poster.jpg",
        summary: `Set in a bright glossy future L.A, this warm and engaging human machine romance has some interesting 
        takes on a well-worn formula`,
        e: 8,
        a: 7,
        n: 7,
        c: 9,
    },
    {
        title: "Host, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/55/The_Host_film_poster.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 4,
        c: 6,
    },
    {
        title: "Hotel Artemis",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/41/Hotel_Artemis_poster.png",
        summary: ``,
        e: 5,
        a: 6,
        n: 5,
        c: 6,
    },
    {
        title: "How It Ends",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/d7/How_It_Ends_%28film%29.png",
        summary: ``,
        e: 3,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "Hunger Games, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/42/HungerGamesPoster.jpg",
        summary: `Like Harry Potter this is a young adult blockbuster which ends up being less dark than its book, but 
        in this case with better acting and a bit of muted social criticism`,
        e: 6,
        a: 7,
        n: 6,
        c: 8,
    },
    {
        title: "I Am Legend",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/df/I_am_legend_teaser.jpg",
        summary: ``,
        e: 6,
        a: 9,
        n: 5,
        c: 6,
    },
    {
        title: "I Am Mother",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a4/I_Am_Mother_poster.png",
        summary: ``,
        e: 8,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "I, Robot",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/3b/Movie_poster_i_robot.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 5,
        c: 3,
    },
    {
        title: "Imposter, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/thumb/3/33/TheImposter2012Poster.jpg/330px-TheImposter2012Poster.jpg",
        summary: ``,
        e: 6,
        a: 4,
        n: 4,
        c: 3,
    },
    {
        title: "Inception",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
        summary: `A cultural phenomenon that overcomes its absurdity and weak characters with blockbuster effects
        and a few intriguing plot hooks, much like the Matrix 11 years earlier`,
        e: 8,
        a: 9,
        n: 8,
        c: 7,
    },
    {
        title: "Independence Day",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/bb/Independence_day_movieposter.jpg",
        summary: ``,
        e: 4,
        a: 6,
        n: 5,
        c: 4,
    },
    {
        title: "Infini",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/94/Infini_poster.png",
        summary: ``,
        e: 3,
        a: 4,
        n: 4,
        c: 3,
    },
    {
        title: "Interstellar",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
        summary: `A behemoth of a movie, the sheer scope and spectacle is enthralling enough to overlook the weak 
        characters and hit-and-miss mystical themes`,
        e: 8,
        a: 8,
        n: 7,
        c: 7,
    },
    {
        title: "IO",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/32/IO_film_poster.jpeg",
        summary: ``,
        e: 7,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "Johnny Mnemonic",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/7b/Johnny_mnemonic_ver1.jpg",
        summary: ``,
        e: 7,
        a: 4,
        n: 3,
        c: 2,
    },
    {
        title: "Jurassic Park",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg",
        summary: `Michael Crichton’s page turner was the perfect Spielberg blockbuster, best watched as a small child
        but really timeless action packed sci-fi for all ages, with a few darker warnings remaining from the novel`,
        e: 9,
        a: 9,
        n: 9,
        c: 6,
    },
    {
        title: "Knowing",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/08/Knowingposter08.jpg",
        summary: ``,
        e: 3,
        a: 6,
        n: 4,
        c: 3,
    },
    {
        title: "Land Of The Dead",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9e/Landofthedead.jpg",
        summary: ``,
        e: 2,
        a: 3,
        n: 3,
        c: 3,
    },
    {
        title: "Lapsis",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/92/Lapsis.jpg",
        summary: `A strong lead character and some clever, offbeat world building overcome the meandering and implausible plot to deliver a memorable critique of the gig economy.`,
        e: 6,
        a: 4,
        n: 5,
        c: 6,
    },
    {
        title: "Last Days On Mars",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/0e/Last_Days_on_Mars_Poster.jpg",
        summary: ``,
        e: 4,
        a: 7,
        n: 4,
        c: 5,
    },
    {
        title: "Last Days, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/thumb/e/ef/The_Last_Days.jpg/330px-The_Last_Days.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 6,
    },
    {
        title: "Life",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/c4/Life_%282017_film%29.png",
        summary: `A tense but not terribly original sci-fi horror which is propelled along by the suspense and 
        character conflicts in its fairly realistic and claustrophobic setting`,
        e: 7,
        a: 8,
        n: 7,
        c: 6,
    },
    {
        title: "Limitless",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/17/Limitless_Poster.jpg",
        summary: ``,
        e: 8,
        a: 6,
        n: 7,
        c: 5,
    },
    {
        title: "Lobster, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9d/The_Lobster_%282015%29_poster.jpg",
        summary: ``,
        e: 5,
        a: 4,
        n: 2,
        c: 3,
    },
    {
        title: "Long Distance",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/22/Distant_2024_poster.jpg",
        summary: `Few enjoyable dark humour moments, characters are a bit annoying but the ecosystem of the world is interesting and nice CGI.`,
        e: 4,
        a: 7,
        n: 5,
        c: 6,
    },
    {
        title: "Looper",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/0a/Looper_poster.jpg",
        summary: `This time travel movie features a clever and surprisingly internally consistent plot, as well as 
        likeable characters and (ignoring the time travel) glimpses of a solidly believable future`,
        e: 7,
        a: 6,
        n: 9,
        c: 7,
    },
    {
        title: "Machine, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/77/TheMachine2013Poster.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 5,
        c: 4,
    },
    {
        title: "Mad Max",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/5a/MadMazAus.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 4,
        c: 5,
    },
    {
        title: "Marjorie Prime",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/ee/Marjorie_Prime.jpg",
        summary: ``,
        e: 5,
        a: 5,
        n: 6,
        c: 6,
    },
    {
        title: "Martian, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg",
        summary: `Andy Weir's upbeat, funny protagonist of science Mark Watney is a perfect fit for Matt Damon, and
         coupled with Ridley Scott's eye for the stunning visuals this is a glorious and very enjoyable movie`,
        e: 8,
        a: 8,
        n: 8,
        c: 8,
    },
    {
        title: "Matrix Reloaded",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/ba/Poster_-_The_Matrix_Reloaded.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 5,
    },
    {
        title: "Matrix Revolutions",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/7b/The-matrix-revolutions_oxlati6t.png",
        summary: ``,
        e: 6,
        a: 7,
        n: 6,
        c: 5,
    },
    {
        title: "Matrix, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png",
        summary: `The Matrix was a groundbreaking and visually stunning sci-fi that survives multiple rewatchings
        due to the tight plot, pop philosophy, and fun action sequences leading up to a satisfying conclusion`,
        e: 9,
        a: 8,
        n: 9,
        c: 6,
    },
    {
        title: "Maze Runner, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/be/The_Maze_Runner_poster.jpg",
        summary: ``,
        e: 4,
        a: 4,
        n: 4,
        c: 3,
    },
    {
        title: "Mercy",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/43/Mercy_2026_poster.jpeg",
        summary: `Sets up an interesting premise and method of storytelling, but fails to deliver`,
        e: 4,
        a: 5,
        n: 6,
        c: 5,
    },
    {
        title: "Mickey 17",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/2d/Mickey_17_film_poster.png",
        summary: `A bit campy but roles are played with gusto and you can’t help wanting to see everyone get their just desserts`,
        e: 5,
        a: 5,
        n: 6,
        c: 8,
    },
    {
        title: "Minority Report",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/44/Minority_Report_Poster.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 5,
        c: 4,
    },
    {
        title: "Mission To Mars",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/c6/Mission_to_mars.jpg",
        summary: ``,
        e: 6,
        a: 5,
        n: 4,
        c: 4,
    },
    {
        title: "Monsters",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/35/MonstersUK.jpg",
        summary: `Jon Hopkins delicate, beautiful score is the perfect accompaniment to this sci-fi romance, and along 
        with the top notch cinematography it brings to life the wonder of the strange alien life in the film's 
        believable devastated landscape, despite the shoestring budget this was shot on`,
        e: 8,
        a: 9,
        n: 8,
        c: 7,
    },
    {
        title: "Moon",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/af/Moon_%282009_film%29.jpg",
        summary: `This minimalistic gem uses a haunting score and few slick effect shots of the 
        indifferent beauty of the moon to perfectly set up an atmosphere of claustrophobic isolation, 
        into which Sam Rockwell delivers a riveting performance through some tightly written plot beats`,
        e: 8,
        a: 10,
        n: 8,
        c: 7,
    },
    {
        title: "Mortal Engines",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/19/MortalEngines2018poster.jpg",
        summary: ``,
        e: 4,
        a: 7,
        n: 4,
        c: 4,
    },
    {
        title: "Mother/Android",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/02/Mother_Android.jpg",
        summary: ``,
        e: 4,
        a: 6,
        n: 4,
        c: 5,
    },
    {
        title: "Mutant Chronicles",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/8f/The_Mutant_Chronicles.jpg",
        summary: ``,
        e: 2,
        a: 4,
        n: 3,
        c: 3,
    },
    {
        title: "Mute",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/82/Mute_poster.png",
        summary: ``,
        e: 4,
        a: 8,
        n: 4,
        c: 6,
    },
    {
        title: "Narcopolis",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/b4/Narcopolis_%28film%29.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 3,
        c: 4,
    },
    {
        title: "Never Let Me Go",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/Neverletmegoposterquad.jpg/330px-Neverletmegoposterquad.jpg",
        summary: ``,
        e: 8,
        a: 5,
        n: 5,
        c: 6,
    },
    {
        title: "Oblivion",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/2e/Oblivion2013Poster.jpg",
        summary: ``,
        e: 6,
        a: 8,
        n: 6,
        c: 5,
    },
    {
        title: "On The Beach",
        thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/On_the_Beach_1959_film_poster.jpg/330px-On_the_Beach_1959_film_poster.jpg",
        summary: ``,
        e: 7,
        a: 7,
        n: 5,
        c: 6,
    },
    {
        title: "Osiris Child, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/5f/Osirischildposter.jpg",
        summary: ``,
        e: 3,
        a: 4,
        n: 3,
        c: 3,
    },
    {
        title: "Otherlife",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/8e/Film_poster_for_the_2017_Australian_film_OtherLife.jpg",
        summary: ``,
        e: 6,
        a: 5,
        n: 6,
        c: 6,
    },
    {
        title: "Outland",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/dc/Outland_%28movie_poster%29.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 7,
        c: 6,
    },
    {
        title: "Outside The Wire",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/b8/OutsideTheWire.jpeg",
        summary: ``,
        e: 5,
        a: 7,
        n: 4,
        c: 4,
    },
    {
        title: "Oxygen",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/de/Oxygen_2021_poster.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 3,
        c: 4,
    },
    {
        title: "Pacific Rim",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f3/Pacific_Rim_FilmPoster.jpeg",
        summary: ``,
        e: 3,
        a: 6,
        n: 3,
        c: 3,
    },
    {
        title: "Pandorum",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/3d/Pandorum-Poster.jpg",
        summary: `A slick, bleak, atmospheric sci-fi horror with some great action scenes`,
        e: 7,
        a: 9,
        n: 8,
        c: 6,
    },
    {
        title: "Paradise",
        thumbnail: "https://filmmusicreporter.com/wp-content/uploads/2023/07/vs-24.jpeg",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 6,
    },
    {
        title: "Passengers",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/8e/Passengers_2016_film_poster.jpg",
        summary: `A slick, enjoyable sci-fi rom-com carried by the main characters and special effects`,
        e: 7,
        a: 7,
        n: 8,
        c: 8,
    },
    {
        title: "Pitch Black",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/26/Pitch_Black_poster.JPG",
        summary: ``,
        e: 5,
        a: 6,
        n: 5,
        c: 3,
    },
    {
        title: "Pod Generation, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9c/The_Pod_Generation_poster.jpg",
        summary: `Not much happens in this single-issue sci-fi, and yet the characters play the romance and mild black comedy script well and the world feel close and real`,
        e: 6,
        a: 7,
        n: 4,
        c: 5,
    },
    {
        title: "Predator",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/95/Predator_Movie.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 5,
        c: 3,
    },
    {
        title: "Predestination",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/4b/Predestination_poster.jpg",
        summary: ``,
        e: 7,
        a: 6,
        n: 6,
        c: 6,
    },
    {
        title: "Prometheus",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a3/Prometheusposterfixed.jpg",
        summary: `A more cerebral and big-picture exploration of the origins of Alien, this has the same slow building
        tension although lacks some of the tight focus and attention to detail`,
        e: 9,
        a: 9,
        n: 6,
        c: 7,
    },
    {
        title: "Prospect",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/b0/Prospect_film_poster.jpg",
        summary: ``,
        e: 6,
        a: 7,
        n: 6,
        c: 5,
    },
    {
        title: "Purge, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/94/The_Purge_film_poster.jpg",
        summary: ``,
        e: 5,
        a: 5,
        n: 4,
        c: 4,
    },
    {
        title: "Quiet Place, A",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a0/A_Quiet_Place_film_poster.png",
        summary: ``,
        e: 6,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "Real Steel",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/22/Real_Steel_Poster.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 4,
        c: 4,
    },
    {
        title: "Red Planet",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/72/Redplanetmovieposter.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 5,
        c: 3,
    },
    {
        title: "Reminiscence",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/73/ReminiscencePoster.jpeg",
        summary: `Gorgeous blend of noir and eco-collapse setting, sadly let down by vanilla casting and plot`,
        e: 6,
        a: 9,
        n: 6,
        c: 4,
    },
    {
        title: "Replicas",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/c9/Replicas_poster.jpg",
        summary: ``,
        e: 2,
        a: 3,
        n: 2,
        c: 2,
    },
    {
        title: "Rise of the planet of the apes",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/81/Rise_of_the_Planet_of_the_Apes_Poster.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 3,
        c: 4,
    },
    {
        title: "Riverworld",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/2f/Riverworlddvd.jpg",
        summary: ``,
        e: 8,
        a: 6,
        n: 5,
        c: 5,
    },
    {
        title: "Robocop (2014)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/2c/RoboCop_%282014_film%29_poster.jpg",
        summary: ``,
        e: 7,
        a: 5,
        n: 5,
        c: 6,
    },
    {
        title: "Robot & Frank",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/40/Robot_and_frank_poster.jpg",
        summary: ``,
        e: 6,
        a: 5,
        n: 5,
        c: 6,
    },
    {
        title: "Running Man, The (2025)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/49/The_Running_Man_2025_poster.jpg",
        summary: `Funny and enjoyable remake, the corporate dystopia is unoriginal but handled with robocop-esque dark humour which works well`,
        e: 4,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "Rupture",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/92/Rupture_%28film%29.jpg",
        summary: ``,
        e: 3,
        a: 4,
        n: 3,
        c: 4,
    },
    {
        title: "Screamers",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/eb/Screamersposter.jpg",
        summary: ``,
        e: 6,
        a: 7,
        n: 7,
        c: 5,
    },
    {
        title: "Sea Fever",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9f/Sea_Fever_%282019%29_poster.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 6,
        c: 5,
    },
    {
        title: "Self/less",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a3/Selfless_poster.jpg",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 5,
    },
    {
        title: "Serenity",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9e/Serenity_One_Sheet.jpg",
        summary: `A space opera that carries the fun free-wheeling libertarian ethos over from Firefly, but it doesn't 
        quite deliver as well in a full length movie format`,
        e: 6,
        a: 7,
        n: 7,
        c: 7,
    },
    {
        title: "Settlers",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/2d/Settlers_%282021_movie_poster%29.jpg",
        summary: ``,
        e: 3,
        a: 6,
        n: 5,
        c: 4,
    },
    {
        title: "Simulant",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/3c/Simulant_poster.jpg",
        summary: `A shallow noir about humanoid robots, the atmosphere and characters are reasonable but it never lives up to its potential`,
        e: 5,
        a: 6,
        n: 5,
        c: 6,
    },
    {
        title: "Slingshot",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a8/Slingshot_%282024%29_poster.jpg",
        summary: `Quite watchable space based psychological thriller with a bit of a shaky premise and characterisation`,
        e: 5,
        a: 6,
        n: 7,
        c: 5,
    },
    {
        title: "Solar Crisis",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/15/Solar_Crisis_FilmPoster.jpeg",
        summary: ``,
        e: 4,
        a: 5,
        n: 3,
        c: 3,
    },
    {
        title: "Solaris (2002)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/bf/Solaris2002poster.jpg",
        summary: `Soderbergh's adaptation is more approachable and less cerebral than Tarkovsky's due to his focus
        on the character relationships rather than the larger metaphysical concerns of the novel, and this angle 
        ultimately yields an enjoyable and well told tale`,
        e: 9,
        a: 8,
        n: 8,
        c: 8,
    },
    {
        title: "Source Code",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e5/Source_Code_Poster.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 7,
        c: 6,
    },
    {
        title: "Soylent Green",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/13/Soylent_green.jpg",
        summary: ``,
        e: 7,
        a: 6,
        n: 6,
        c: 6,
    },
    {
        title: "Space Between Us, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/78/The_Space_Between_Us_poster.jpg",
        summary: ``,
        e: 5,
        a: 5,
        n: 3,
        c: 3,
    },
    {
        title: "Spectral",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Spectral_%28Title_Card%29.jpg/330px-Spectral_%28Title_Card%29.jpg",
        summary: ``,
        e: 6,
        a: 7,
        n: 6,
        c: 6,
    },
    {
        title: "Sphere",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/ac/Spheremovieposter.jpg",
        summary: ``,
        e: 6,
        a: 4,
        n: 4,
        c: 4,
    },
    {
        title: "Sputnik",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a9/Sputnik_%282020%29_poster.jpg",
        summary: `A punchy, back-to-basics Russian sci-fi that injects some introspection and novelty into a well worn formula`,
        e: 7,
        a: 7,
        n: 8,
        c: 7,
    },
    {
        title: "Stake Land",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/7c/Stake_Land_%28film%29.jpg",
        summary: ``,
        e: 1,
        a: 3,
        n: 2,
        c: 2,
    },
    {
        title: "Stalker",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/d4/Stalker_poster.jpg",
        summary: `Like a sci-fi Mulholland Drive, this film's dreamy and hypnotic shots pack a much more powerful punch 
        than Solaris (or 2001 for that matter) and effectively bring the difficult cerebral concepts in Roadside Picnic 
        to life in a deeply visceral and intuitive way.`,
        e: 8,
        a: 9,
        n: 3,
        c: 7,
    },
    {
        title: "Star Trek II: The Wrath of Khan",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9a/Star_Trek_II_The_Wrath_of_Khan.png",
        summary: ``,
        e: 5,
        a: 4,
        n: 5,
        c: 5,
    },
    {
        title: "Stowaway",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/7/75/Stowaway_2021_Film_poster.png",
        summary: ``,
        e: 3,
        a: 6,
        n: 4,
        c: 5,
    },
    {
        title: "Strange Days",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/0c/Strangedays.jpeg",
        summary: `Kathryn Bigelow's underrated cyberpunk noir is a whirlwind drive through the last days of the 20th
        century, foreshadowing the issues of the 21st with its backdrop of a dysfunctional society and a confronting 
        series of virtually experienced murders`,
        e: 8,
        a: 7,
        n: 7,
        c: 8,
    },
    {
        title: "Sunshine",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/68/Sunshine_poster.jpg",
        summary: `Stunning cinematography, a solid cast, and interesting premise mostly overcome the weird metaphysical 
        elements in the screenplay, although the second half is much weaker than the first`,
        e: 8,
        a: 10,
        n: 5,
        c: 7,
    },
    {
        title: "Supernova",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/0a/Supernova_ver1.jpg",
        summary: ``,
        e: 5,
        a: 5,
        n: 4,
        c: 4,
    },
    {
        title: "Synchronic",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f5/Synchronic_poster.jpeg",
        summary: `Screenwriter does reasonable job of tying together a difficult but ultimately rewarding high concept, despite some implausible scenes along the way.`,
        e: 3,
        a: 6,
        n: 6,
        c: 7,
    },
    {
        title: "Terminator",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/6d/The_Terminator.png",
        summary: ``,
        e: 6,
        a: 7,
        n: 6,
        c: 7,
    },
    {
        title: "Terminator 2 - Judgement Day",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/5e/Terminator_2-Judgment_Day.png",
        summary: ``,
        e: 6,
        a: 7,
        n: 5,
        c: 7,
    },
    {
        title: "These Final Hours",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/9/9c/These_Final_Hours.jpg",
        summary: ``,
        e: 4,
        a: 5,
        n: 5,
        c: 5,
    },
    {
        title: "Thing, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e3/The_Thing_%281982_film%29.png",
        summary: ``,
        e: 5,
        a: 5,
        n: 5,
        c: 4,
    },
    {
        title: "Tides",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/e5/Tides_film_poster.jpg",
        summary: `An enjoyable fast moving sci-fi, largely carried by the cinematography and Nora Arnezeder’s character`,
        e: 6,
        a: 7,
        n: 7,
        c: 6,
    },
    {
        title: "THX 1138",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/56/THX1138.jpg",
        summary: ``,
        e: 4,
        a: 3,
        n: 2,
        c: 2,
    },
    {
        title: "Time Machine, The (2002)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/6f/Time_machine.jpg",
        summary: ``,
        e: 6,
        a: 5,
        n: 3,
        c: 2,
    },
    {
        title: "Titan, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/dd/The_Titan_poster.png",
        summary: `A solid but slightly unfocused narrative which treads a fair bit of new ground but never quite takes 
        off`,
        e: 8,
        a: 7,
        n: 6,
        c: 7,
    },
    {
        title: "Tomorrow War, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/60/The_Tomorrow_War_%282021_film%29_official_theatrical_poster.jpg",
        summary: `A fast and fun popcorn flick that manages to land a few hits on some topical issues without taking itself too seriously`,
        e: 6,
        a: 8,
        n: 6,
        c: 7,
    },
    {
        title: "Total Recall",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/a/a5/TotalRecall2012Poster.jpg",
        summary: ``,
        e: 7,
        a: 7,
        n: 7,
        c: 4,
    },
    {
        title: "Transcendence",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/ef/Transcendence2014Poster.jpg",
        summary: ``,
        e: 7,
        a: 8,
        n: 5,
        c: 5,
    },
    {
        title: "Tremors",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f1/Tremors_official_theatrical_poster.jpg",
        summary: ``,
        e: 3,
        a: 4,
        n: 5,
        c: 5,
    },
    {
        title: "Uncanny",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/63/Uncanny_poster.jpg",
        summary: ``,
        e: 6,
        a: 4,
        n: 5,
        c: 4,
    },
    {
        title: "Underwater",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/4a/Underwater_poster.jpeg",
        summary: ``,
        e: 3,
        a: 7,
        n: 5,
        c: 5,
    },
    {
        title: "Upgrade",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/24/UpgradePoster.jpg",
        summary: `Fast paced, grimy cyberpunk flick featuring some interesting tech without delving too much into the implications`,
        e: 8,
        a: 7,
        n: 7,
        c: 7,
    },
    {
        title: "Valerian and the City of a Thousand Planets",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/0/07/Valerian_and_the_City_of_a_Thousand_Planets.jpg",
        summary: ``,
        e: 3,
        a: 6,
        n: 5,
        c: 3,
    },
    {
        title: "Vanilla Sky",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/2d/Vanilla_Sky_poster.png",
        summary: ``,
        e: 5,
        a: 5,
        n: 6,
        c: 7,
    },
    {
        title: "Vesper",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/38/Vesper_film_poster.png",
        summary: `Novel biopunk setting`,
        e: 7,
        a: 6,
        n: 6,
        c: 5,
    },
    {
        title: "WALL-E",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg",
        summary: `My favourite Pixar movie, Stanton's subtle screenplay turns what could have been a brain-dead kids
        movie into a touching and intelligent sci-fi`,
        e: 8,
        a: 8,
        n: 7,
        c: 6,
    },
    {
        title: "Wandering Earth, The",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/1/1b/The_Wandering_Earth_film_poster.jpg",
        summary: ``,
        e: 6,
        a: 6,
        n: 4,
        c: 3,
    },
    {
        title: "War Of The Worlds (2005)",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/83/War_of_the_Worlds_2005_poster.jpg",
        summary: `There is something very cathartic about the deadbeat dad redemption and post 9-11 trauma themes
        worked throughout, and along with the effective build up of tension and amazing special effects, that makes 
        this an extremely enjoyable movie`,
        e: 7,
        a: 9,
        n: 9,
        c: 8,
    },
    {
        title: "WarGames",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/29/Wargames.jpg",
        summary: ``,
        e: 6,
        a: 5,
        n: 5,
        c: 4,
    },
    {
        title: "Waterworld",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/5f/Waterworld.jpg",
        summary: `Sure the characterisation is weak and the world building could have been more subtle, but the ascetic 
        is top notch and every scene in this epic blockbuster is perfectly conceived and executed and they connect 
        together into an intriguing and satisfying experience`,
        e: 8,
        a: 10,
        n: 8,
        c: 3,
    },
    {
        title: "What Happened to Monday?",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/f/f2/What_Happened_to_Monday.png",
        summary: ``,
        e: 5,
        a: 6,
        n: 6,
        c: 6,
    },
    {
        title: "World War Z",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/d/dc/World_War_Z_poster.jpg",
        summary: `This tense and visually stunning zombie movie sneaks enough science into its slower third act to 
        consider it a sci-fi, and for the rest is a enjoyable and smart series of fast paced action set pieces`,
        e: 6,
        a: 9,
        n: 7,
        c: 7,
    },
    {
        title: "Zone 414",
        thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/b8/Zone_four_one_four.jpg",
        summary: `Tries hard to create an engaging atmosphere and characters and at times almost succeeds`,
        e: 5,
        a: 6,
        n: 5,
        c: 6,
    },
];