import type { MetaDescriptor } from "react-router";

export const SITE_URL = "https://iondrive.co";
export const SITE_NAME = "Iondrive";

const DEFAULT_DESCRIPTION =
  "Creative writing, opinions, projects, and links — a personal site by Miles.";

/** Default social-share image (1200×630). Generated by scripts/gen-og-image.mjs. */
const DEFAULT_OG_IMAGE = `${SITE_URL}/og-image.png`;

type SeoArgs = {
  /** Page title without the site-name suffix. Omit for the homepage. */
  title?: string;
  /** Meta description. Falls back to a site-wide default. */
  description?: string;
  /** Canonical path beginning with "/", e.g. "/Reviews". Omit for the homepage. */
  path?: string;
  /** Emit a noindex robots tag (e.g. for 404 / not-found states). */
  noIndex?: boolean;
  /** Open Graph type. Defaults to "website"; use "article" for content pages. */
  type?: "website" | "article";
  /** Absolute URL of a social-share image. Defaults to the site OG image. */
  image?: string;
  /** One or more JSON-LD objects to embed as <script type="application/ld+json">. */
  jsonLd?: Record<string, unknown> | Record<string, unknown>[];
};

/**
 * Build a complete set of meta descriptors for a route: title, description,
 * canonical link, Open Graph + Twitter Card tags, and optional JSON-LD. Each
 * route's meta replaces its parent's in React Router, so the result is
 * self-contained.
 */
export function seo({
  title,
  description,
  path,
  noIndex,
  type = "website",
  image,
  jsonLd,
}: SeoArgs = {}): MetaDescriptor[] {
  const fullTitle = title ? `${title} — ${SITE_NAME}` : SITE_NAME;
  const desc = description ?? DEFAULT_DESCRIPTION;
  const canonical = path ? `${SITE_URL}${path}` : SITE_URL;
  const ogImage = image ?? DEFAULT_OG_IMAGE;

  const descriptors: MetaDescriptor[] = [
    { title: fullTitle },
    { name: "description", content: desc },
    { tagName: "link", rel: "canonical", href: canonical },
    { property: "og:title", content: fullTitle },
    { property: "og:description", content: desc },
    { property: "og:type", content: type },
    { property: "og:url", content: canonical },
    { property: "og:site_name", content: SITE_NAME },
    { property: "og:image", content: ogImage },
    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:title", content: fullTitle },
    { name: "twitter:description", content: desc },
    { name: "twitter:image", content: ogImage },
  ];

  if (noIndex) {
    descriptors.push({ name: "robots", content: "noindex, nofollow" });
  }

  if (jsonLd) {
    for (const block of Array.isArray(jsonLd) ? jsonLd : [jsonLd]) {
      descriptors.push({ "script:ld+json": block });
    }
  }

  return descriptors;
}

/** Collapse whitespace and truncate to `max` chars at a word boundary. */
export function truncate(text: string, max = 155): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  return (lastSpace > 0 ? cut.slice(0, lastSpace) : cut).trimEnd() + "…";
}

/** Escape a string for inclusion in XML text/attribute content. */
export function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
